import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

import { Cairo } from 'next/font/google'
import Header from "./components/header/Header";

const cairo = Cairo({
  subsets: ['arabic'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-cairo',
})
type Props = {
  children: ReactNode;
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ar" dir="rtl" >
      <body
        className={`$ ${cairo.className} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
