// import { Geist, Geist_Mono } from "next/font/google";
// import { ReactNode } from "react";
// import "../../globals.css";

// import { Cairo } from 'next/font/google'
// import Header from "../../components/header/Header";

// const cairo = Cairo({
//   subsets: ['arabic'],
//   weight: ['400', '700'],
//   display: 'swap',
//   variable: '--font-cairo',
// })
// type Props = {
//   children: ReactNode;
// };

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: Props) {
//   return (
//     <html lang="ar" dir="rtl"  >
//       <body
//         className={`$ ${cairo.className} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import { ReactNode } from "react";
import Header from "../../components/admin/Header";
import Sidebar from "../../components/admin/Sidebar";

type Props = {
  children: ReactNode;
};

export default function AuthLayout({ children }: Props) {
  return (
    <div>
      <Header />
      <div className="flex">
      <div className="w-60 bg-gray-300 h-[calc(100vh-4rem)]">    <Sidebar /></div>
      {children}
      </div>
    </div>
  );
}